run:
  deadline: 10m10s
  modules-download-mode: vendor
  go: 1.17

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - ifshort
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - noctx
    - makezero
    - misspell
    #- paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - structcheck
    - stylecheck
    - revive
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
    - vet
    - vetshadow
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  errcheck:
    ignore: io:Close
  misspell:
    locale: uk
    ignore-words:
      - color # is there a way to only ignore package names?
  nlreturn:
    block-size: 4
