dist: xenial
sudo: required
services:
  - docker
language: go
go:
  - "1.13.x"

branches:
  only:
    - master

env:
  global:
    GOFLAGS=-mod=vendor
    GOOGLE_PROVIDER_URI="https://releases.hashicorp.com/terraform-provider-google/3.10.0/terraform-provider-google_3.10.0_linux_amd64.zip?checksum=sha256:5ccd58dd5792d2bc3bf3ccf8e09906a1709f9496e501de287554dfe86940f454"

install:
  - make tools
  - wget ${GOOGLE_PROVIDER_URI} -O /tmp/tmp.zip && mkdir -p $HOME/.terraform.d/plugins && unzip /tmp/tmp.zip -d $HOME/.terraform.d/plugins && rm /tmp/tmp.zip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "make lint"
      script: make lint
    - name: "make test"
      script: make test
