---
name: test
on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./.go-version
      - run: make test
